[package]
authors = ["Bastien Dejean <nihilhill@gmail.com>"]
name = "plato"
version = "0.9.44"
edition = "2021"

[[bin]]
name = "plato"
path = "src/main.rs"

[dependencies]
plato-core = { path = "../core" }
once_cell = "1"
regex = "1"