name: Build Plato for Kobo

on:
  push:
    branches: [ "**" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake pkg-config \
              wget unzip tar xz-utils \
              libfreetype6-dev zlib1g-dev libzip-dev \
              libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev libsdl2-mixer-dev

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Plato provides helper scripts; we'll use them for Kobo cross build
      - name: Download toolchains
        run: bash ./download.sh kobo

      - name: Build (release) for Kobo
        run: bash ./build.sh kobo release

      - name: Bundle ZIP
        run: bash ./bundle.sh kobo

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: plato-kobo-zip
          path: dist/plato-kobo.zip
